interface ReportEmailParams {
  pmfScore: number;
  pmfStage: string;
  verdict: string;
  reportUrl: string;
}

function escapeHtml(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function stageColor(stage: string): string {
  const s = (stage || '').toLowerCase();
  if (s.includes('strong')) return '#065f46';
  if (s.includes('good') || s.includes('solid')) return '#047857';
  if (s.includes('moderate') || s.includes('emerging')) return '#92400e';
  return '#991b1b';
}

export function buildReportEmailHtml(params: ReportEmailParams): string {
  const { pmfScore, pmfStage, verdict, reportUrl } = params;
  const safeVerdict = escapeHtml(verdict || '');
  const safeStage = escapeHtml(pmfStage || 'Unknown');
  const badgeColor = stageColor(pmfStage);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Your PMF Insights Report</title>
</head>
<body style="margin:0;padding:0;background-color:#f9fafb;font-family:Arial,Helvetica,sans-serif;color:#1a1a1a;">
  <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background-color:#f9fafb;">
    <tr>
      <td align="center" style="padding:24px 16px;">
        <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;width:100%;background-color:#ffffff;border-radius:8px;overflow:hidden;">
          <!-- Header -->
          <tr>
            <td style="background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);padding:32px 24px;text-align:center;">
              <h1 style="margin:0;font-size:24px;font-weight:700;color:#ffffff;letter-spacing:0.5px;">PMF Insights</h1>
            </td>
          </tr>

          <!-- Greeting -->
          <tr>
            <td style="padding:32px 24px 16px;">
              <h2 style="margin:0;font-size:20px;font-weight:600;color:#1a1a1a;text-align:center;">Your PMF Insights Report is Ready</h2>
            </td>
          </tr>

          <!-- Score Highlight -->
          <tr>
            <td align="center" style="padding:16px 24px;">
              <table role="presentation" cellpadding="0" cellspacing="0" border="0">
                <tr>
                  <td align="center" style="padding:16px 32px;background-color:#f3f4f6;border-radius:8px;">
                    <div style="font-size:48px;font-weight:700;color:#667eea;line-height:1.1;">${Math.round(pmfScore)}</div>
                    <div style="font-size:13px;color:#6b7280;margin-top:4px;">PMF Score</div>
                    <div style="margin-top:8px;">
                      <span style="display:inline-block;background-color:${badgeColor};color:#ffffff;padding:4px 12px;border-radius:12px;font-size:12px;font-weight:600;">${safeStage}</span>
                    </div>
                  </td>
                </tr>
              </table>
            </td>
          </tr>

          <!-- Verdict -->
          ${safeVerdict ? `<tr>
            <td style="padding:8px 24px 24px;">
              <p style="margin:0;font-size:15px;color:#374151;text-align:center;font-style:italic;line-height:1.5;">${safeVerdict}</p>
            </td>
          </tr>` : ''}

          <!-- CTA Button -->
          <tr>
            <td align="center" style="padding:8px 24px 32px;">
              <a href="${reportUrl}" target="_blank" style="display:inline-block;background-color:#667eea;color:#ffffff;padding:12px 24px;border-radius:6px;text-decoration:none;font-size:15px;font-weight:600;">View Full Report</a>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="padding:24px;border-top:1px solid #e5e7eb;text-align:center;">
              <p style="margin:0;font-size:13px;color:#6b7280;line-height:1.5;">This report was generated by PMF Insights Tool. The attached PDF contains your full report.</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
}
