export interface ReportPdfData {
  pmfScore: number;
  pmfStage: string;
  primaryBreak: string;
  content: Record<string, any>;
  scores: Array<{ name: string; score: number; weight: number; verdict: string }>;
}

function escapeHtml(str: string): string {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function severityBadge(score: number): string {
  if (score <= 3) {
    return `<span style="background:#fee2e2;color:#991b1b;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;">Critical</span>`;
  }
  if (score <= 6) {
    return `<span style="background:#fef3c7;color:#92400e;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;">Moderate</span>`;
  }
  return `<span style="background:#d1fae5;color:#065f46;padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600;">Strong</span>`;
}

function stageColor(stage: string): string {
  const s = (stage || '').toLowerCase();
  if (s.includes('strong')) return '#065f46';
  if (s.includes('moderate')) return '#92400e';
  return '#991b1b';
}

function formatDate(): string {
  return new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

const footer = `<div style="text-align:center;color:#6b7280;font-size:10px;padding-top:20px;border-top:1px solid #e5e7eb;margin-top:40px;">Generated by PMF Insights Tool</div>`;

function sectionWrapper(title: string, body: string): string {
  return `
    <div style="page-break-before:always;padding:2cm 1.5cm;">
      <h2 style="color:#374151;font-size:22px;border-bottom:2px solid #667eea;padding-bottom:8px;margin-bottom:20px;">${escapeHtml(title)}</h2>
      ${body}
      ${footer}
    </div>`;
}

function renderCoverPage(data: ReportPdfData): string {
  return `
    <div style="height:100vh;display:flex;flex-direction:column;justify-content:center;align-items:center;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;text-align:center;padding:2cm;">
      <h1 style="font-size:42px;margin-bottom:10px;font-weight:300;letter-spacing:2px;">PMF Insights Report</h1>
      <div style="font-size:96px;font-weight:700;margin:30px 0;">${data.pmfScore}<span style="font-size:36px;font-weight:300;">/100</span></div>
      <div style="display:inline-block;background:rgba(255,255,255,0.2);padding:8px 24px;border-radius:20px;font-size:18px;margin-bottom:20px;">${escapeHtml(data.pmfStage)}</div>
      <div style="font-size:14px;opacity:0.8;margin-top:10px;">${formatDate()}</div>
      ${data.primaryBreak ? `<div style="font-size:14px;opacity:0.9;margin-top:16px;">Primary Break: ${escapeHtml(data.primaryBreak)}</div>` : ''}
    </div>`;
}

function renderScorecard(scores: ReportPdfData['scores']): string {
  if (!scores || scores.length === 0) return '';
  const rows = scores
    .map(
      (s) => `
    <tr>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;font-weight:500;">${escapeHtml(s.name)}</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:center;font-weight:600;">${s.score}/10</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">${(s.weight * 100).toFixed(0)}%</td>
      <td style="padding:10px 12px;border-bottom:1px solid #e5e7eb;">${severityBadge(s.score)} ${escapeHtml(s.verdict)}</td>
    </tr>`,
    )
    .join('');

  return sectionWrapper(
    'PMF Scorecard',
    `<table style="width:100%;border-collapse:collapse;font-size:14px;">
      <thead>
        <tr style="background:#f3f4f6;">
          <th style="padding:10px 12px;text-align:left;font-weight:600;border-bottom:2px solid #d1d5db;">Dimension</th>
          <th style="padding:10px 12px;text-align:center;font-weight:600;border-bottom:2px solid #d1d5db;">Score</th>
          <th style="padding:10px 12px;text-align:center;font-weight:600;border-bottom:2px solid #d1d5db;">Weight</th>
          <th style="padding:10px 12px;text-align:left;font-weight:600;border-bottom:2px solid #d1d5db;">Verdict</th>
        </tr>
      </thead>
      <tbody>${rows}</tbody>
    </table>`,
  );
}

function renderRealityCheck(content: Record<string, any>): string {
  const header = content.header;
  const rc = content.reality_check;
  if (!header && !rc) return '';

  let body = '';
  if (header?.verdict) {
    body += `<p style="font-size:16px;font-weight:600;color:#374151;margin-bottom:16px;">${escapeHtml(header.verdict)}</p>`;
  }
  if (rc) {
    const text = typeof rc === 'string' ? rc : rc.summary || rc.analysis || JSON.stringify(rc);
    body += `<p style="font-size:14px;line-height:1.7;color:#4b5563;">${escapeHtml(String(text))}</p>`;
  }
  return sectionWrapper('Reality Check', body);
}

function renderMarket(content: Record<string, any>): string {
  const market = content.market;
  if (!market) return '';

  let body = '';
  if (market.tam || market.sam || market.growth_rate) {
    body += `<table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:20px;">
      <thead><tr style="background:#f3f4f6;">
        <th style="padding:10px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Metric</th>
        <th style="padding:10px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Value</th>
      </tr></thead>
      <tbody>
        ${market.tam ? `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:500;">TAM</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">${escapeHtml(String(market.tam))}</td></tr>` : ''}
        ${market.sam ? `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:500;">SAM</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">${escapeHtml(String(market.sam))}</td></tr>` : ''}
        ${market.growth_rate ? `<tr><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:500;">Growth Rate</td><td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">${escapeHtml(String(market.growth_rate))}</td></tr>` : ''}
      </tbody>
    </table>`;
  }

  if (market.summary || market.analysis) {
    const text = market.summary || market.analysis;
    body += `<p style="font-size:14px;line-height:1.7;color:#4b5563;">${escapeHtml(String(text))}</p>`;
  }

  return body ? sectionWrapper('Market Analysis', body) : '';
}

function renderCompetitors(content: Record<string, any>): string {
  const comp = content.competitors;
  if (!comp?.companies || comp.companies.length === 0) return '';

  const rows = comp.companies
    .map(
      (c: any) => `
    <tr>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-weight:500;">${escapeHtml(c.name || '')}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">${escapeHtml(c.tagline || '')}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">${c.g2_rating ?? '-'}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;">${escapeHtml(c.pricing_model || '')}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;text-align:center;">${c.free_tier ? 'Yes' : 'No'}</td>
    </tr>`,
    )
    .join('');

  return sectionWrapper(
    'Competitive Landscape',
    `<table style="width:100%;border-collapse:collapse;font-size:13px;">
      <thead><tr style="background:#f3f4f6;">
        <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Company</th>
        <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Tagline</th>
        <th style="padding:8px 12px;text-align:center;border-bottom:2px solid #d1d5db;">G2 Rating</th>
        <th style="padding:8px 12px;text-align:left;border-bottom:2px solid #d1d5db;">Pricing</th>
        <th style="padding:8px 12px;text-align:center;border-bottom:2px solid #d1d5db;">Free Tier</th>
      </tr></thead>
      <tbody>${rows}</tbody>
    </table>`,
  );
}

function renderTextSection(title: string, data: any): string {
  if (!data) return '';
  const text = typeof data === 'string' ? data : data.summary || data.analysis || data.content || '';
  if (!text) return '';
  return sectionWrapper(title, `<p style="font-size:14px;line-height:1.7;color:#4b5563;">${escapeHtml(String(text))}</p>`);
}

function renderBottomLine(content: Record<string, any>, pmfStage: string): string {
  const bl = content.bottom_line;
  if (!bl) return '';
  const text = typeof bl === 'string' ? bl : bl.summary || bl.analysis || bl.content || '';
  if (!text) return '';
  const color = stageColor(pmfStage);
  return sectionWrapper(
    'Bottom Line',
    `<div style="border-left:4px solid ${color};padding:16px 20px;background:#f9fafb;border-radius:0 8px 8px 0;margin-bottom:20px;">
      <p style="font-size:15px;line-height:1.7;color:#374151;margin:0;">${escapeHtml(String(text))}</p>
    </div>`,
  );
}

function renderRecommendations(content: Record<string, any>): string {
  const rec = content.recommendations;
  if (!rec?.items || rec.items.length === 0) return '';

  const items = rec.items
    .map(
      (r: any, i: number) => `
    <div style="margin-bottom:16px;padding:12px 16px;background:#f9fafb;border-radius:8px;border-left:3px solid #667eea;">
      <p style="font-size:14px;font-weight:600;color:#374151;margin:0 0 4px 0;">${i + 1}. ${escapeHtml(r.title || '')}</p>
      <p style="font-size:13px;color:#4b5563;margin:0;line-height:1.6;">${escapeHtml(r.description || '')}</p>
      ${r.priority ? `<span style="font-size:11px;color:#6b7280;margin-top:4px;display:inline-block;">Priority: ${escapeHtml(String(r.priority))}</span>` : ''}
    </div>`,
    )
    .join('');

  return sectionWrapper('Recommendations', items);
}

function renderSources(content: Record<string, any>): string {
  const sources = content.sources;
  if (!sources) return '';

  let body = '';
  if (Array.isArray(sources)) {
    body = `<ul style="font-size:13px;line-height:1.8;color:#4b5563;">${sources.map((s: any) => `<li>${escapeHtml(typeof s === 'string' ? s : s.url || s.title || JSON.stringify(s))}</li>`).join('')}</ul>`;
  } else if (typeof sources === 'object' && sources.items) {
    body = `<ul style="font-size:13px;line-height:1.8;color:#4b5563;">${sources.items.map((s: any) => `<li>${escapeHtml(typeof s === 'string' ? s : s.url || s.title || JSON.stringify(s))}</li>`).join('')}</ul>`;
  } else {
    body = `<p style="font-size:13px;color:#4b5563;">${escapeHtml(String(sources))}</p>`;
  }

  return sectionWrapper('Sources & References', body);
}

export function buildReportHtml(report: ReportPdfData): string {
  const content = report.content || {};

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    @page { margin: 0; }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      color: #1a1a1a;
      line-height: 1.5;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }
    h2 { page-break-after: avoid; }
    table { page-break-inside: avoid; }
  </style>
</head>
<body>
  ${renderCoverPage(report)}
  ${renderScorecard(report.scores)}
  ${renderRealityCheck(content)}
  ${renderMarket(content)}
  ${renderCompetitors(content)}
  ${renderTextSection('Sales Model', content.sales_model)}
  ${renderTextSection('Positioning', content.positioning)}
  ${renderBottomLine(content, report.pmfStage)}
  ${renderRecommendations(content)}
  ${renderSources(content)}
</body>
</html>`;
}
